%% Comments
% Function that array of string in a GUI and return the selected item

%Author: V. Doguet (31/01/2019)
%Updates:
%% Function
function choice = popupdlg(inputList, defaultAnsw, text)

%Allocate
choice = [];

%Create GUI
ftemp = figure('Name', 'pop-up menu dialog', 'NumberTitle', 'off', ...
    'Menu', 'none', ...
    'Position', .1 * get(0, 'ScreenSize'), ...
    'Visible', 'off', ...
    'Resize', 'off', ...
    'CloseRequestFcn', @cancel);

%scrolldown menu
sd = uicontrol('Parent', ftemp, ...
    'Style', 'popup', ...
    'Units', 'normalized', ...
    'Position', [.1, .5, .8, .2], ...
    'String', inputList);

%Set default answer
if exist('defaultAnsw', 'var') && ~isempty(defaultAnsw)
    set(sd, 'Value', defaultAnsw)
end

%Set text to prompt
if exist('text', 'var')
    uicontrol('Parent', ftemp, ...
    'Style', 'text', ...
    'Units', 'normalized', ...
    'Position', [.1, .75, .8, .2], ...
    'String', text, ...
    'FontWeight', 'bold')
end

uicontrol('Parent', ftemp, ...
    'Style', 'pushbutton', ...
    'Units', 'normalized', ...
    'Position', [.1, .1, .3, .3], ...
    'String', 'Select', ...
    'Callback', @select)
uicontrol('Parent', ftemp, ...
    'Style', 'pushbutton', ...
    'Units', 'normalized', ...
    'Position', [.6, .1, .3, .3], ...
    'String', 'Cancel', ...
    'Callback', @cancel)

movegui(ftemp, 'center')
uiwait(ftemp)
delete(ftemp)

    function select(~, ~)
        choice = sd.Value;
        uiresume(ftemp)
    end

    function cancel(~, ~)
        delete(ftemp)
    end
end